import Layout from "./Layout"
import Hero from "./Hero"
import About from "./About"
import Projects from "./Projects"
import Survey from "./Survey"
import Slider from "./Slider"
import Algolia from "./Algolia"
import GridProjects from "./GridProjects"
import SEO from "./SEO"
export { Layout, Hero, About, Projects, Survey, Slider, Algolia, GridProjects, SEO };
